on:
  pull_request:
    branch:
      - dev
    types:
      - closed



jobs:
  CI_CD:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.base.ref}}

      - name: gradle bootJar
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: make log
        run: |
          echo hello world
          echo ${{github.event.pull_request.head.ref}}
          echo ${{github.event.pull_request.base.ref}}

      - name: build procedure
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          java -jar ./build/libs/demo*.jar