on:
  pull_request:
    branch:
      - be/main
    types:
      - closed

jobs:
  CI_CD:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: gradle bootJar
        uses: actions/setup-java@v3
        with:
          arguments: |
            ./gradlew build
            java -jar ./build/libs/demo*.jar
          argument: echo Hello
