on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  CI_CD:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: ssh connection
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEM }},
          HOSTNAME: ${{ secrets.EC2_HOST }},
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            touch iamin
          '
# FTP를 사용하려 했던 흔적
#
#      - name: gradle bootJar
#        uses: actions/setup-java@v3
#        with:
#          java-version: 11
#          distribution: temurin
#
#      - name: make log
#        run: |
#          git branch
#          echo hello world
## test => dev 상황에서 다음과 같이 출력된다.
## test
#          echo ${{github.event.pull_request.head.ref}}
## dev
#          echo ${{github.event.pull_request.base.ref}}
#
#      - name: build procedure
#        run: |
#          chmod +x gradlew
#          ./gradlew bootJar
#          java -jar ./build/libs/demo*.jar